common_sqlite3_flags := \
			-DNDEBUG=1 \
			-DHAVE_USLEEP=1 \
			-DHAVE_READLINE=0 \
			-DSQLITE_THREADSAFE=2 \
			-DSQLITE_TEMP_STORE=3  \
            -DSQLITE_MAX_TRIGGER_DEPTH=20 \
			-DSQLITE_POWERSAFE_OVERWRITE=0 \
			-DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 \
			-DSQLITE_DEFAULT_AUTOVACUUM=0 \
            -DSQLITE_DEFAULT_FOREIGN_KEYS=1 \
            -DSQLITE_DEFAULT_RECURSIVE_TRIGGERS \
			-DSQLITE_DEFAULT_PAGE_SIZE=2048 \
			-DSQLITE_DEFAULT_CACHE_SIZE=4000 \
			-DSQLITE_DEFAULT_TEMP_CACHE_SIZE=1000 \
			-DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 \
			-DSQLITE_ENABLE_FTS3 \
			-DSQLITE_ENABLE_FTS3_BACKWARDS \
			-DSQLITE_ENABLE_FTS4 \
			-DSQLITE_ENABLE_RTREE=1 \
			-DSQLITE_ENABLE_COLUMN_METADATA \
			-DSQLITE_ENABLE_STAT2 \
			-DSQLITE_ENABLE_LOAD_EXTENSION \
			-DSQLITE_ENABLE_AUTO_LOAD_EXTENSION \
			-DSQLITE_OMIT_BUILTIN_TEST \
			-DSQLITE_OMIT_COMPLEOPTION_DIAGS \
			-DSQLITE_OMIT_DEPRECATED \
			-DSQLITE_HAS_CODEC \
			#-DSQLITE_DEFAULT_FILE_FORMAT=4 \
			#-DSQLITE_OS_UNIX=1 \
			#-DSQLITE_THREAD_OVERRIDE_LOCK=-1 \
			#-DSQLITE_ENABLE_FTS3_PARENTHESIS \
			#-DSQLITE_DEFAULT_FILE_PERMISSIONS=0600 \
			#-DSQLITE_HAVE_ISNAN \


ifdef BUILD_ANDROID

common_sqlite3_flags += \
			-DSQLITE_ENABLE_AUTO_LOAD_EXTENSION_ANDROID \

endif

$(info $(common_sqlite3_flags))
